#!/bin/sh
if [ -f /usr/share/rpikernelhack/bcm2708-rpi-0-w.dtb ]; then
	rm -f /boot/bcm2708-rpi-0-w.dtb
	dpkg-divert --package rpikernelhack --remove --rename /boot/bcm2708-rpi-0-w.dtb
	sync
fi
if [ -f /usr/share/rpikernelhack/bcm2708-rpi-b-plus.dtb ]; then
	rm -f /boot/bcm2708-rpi-b-plus.dtb
	dpkg-divert --package rpikernelhack --remove --rename /boot/bcm2708-rpi-b-plus.dtb
	sync
fi
if [ -f /usr/share/rpikernelhack/bcm2708-rpi-b.dtb ]; then
	rm -f /boot/bcm2708-rpi-b.dtb
	dpkg-divert --package rpikernelhack --remove --rename /boot/bcm2708-rpi-b.dtb
	sync
fi
if [ -f /usr/share/rpikernelhack/bcm2708-rpi-cm.dtb ]; then
	rm -f /boot/bcm2708-rpi-cm.dtb
	dpkg-divert --package rpikernelhack --remove --rename /boot/bcm2708-rpi-cm.dtb
	sync
fi
if [ -f /usr/share/rpikernelhack/bcm2709-rpi-2-b.dtb ]; then
	rm -f /boot/bcm2709-rpi-2-b.dtb
	dpkg-divert --package rpikernelhack --remove --rename /boot/bcm2709-rpi-2-b.dtb
	sync
fi
if [ -f /usr/share/rpikernelhack/bcm2710-rpi-3-b.dtb ]; then
	rm -f /boot/bcm2710-rpi-3-b.dtb
	dpkg-divert --package rpikernelhack --remove --rename /boot/bcm2710-rpi-3-b.dtb
	sync
fi
if [ -f /usr/share/rpikernelhack/bcm2710-rpi-cm3.dtb ]; then
	rm -f /boot/bcm2710-rpi-cm3.dtb
	dpkg-divert --package rpikernelhack --remove --rename /boot/bcm2710-rpi-cm3.dtb
	sync
fi
if [ -f /usr/share/rpikernelhack/kernel*.img ]; then
	rm -f /boot/kernel*.img
	dpkg-divert --package rpikernelhack --remove --rename /boot/kernel*.img
	sync
fi
if [ -f /usr/share/rpikernelhack/COPYING.linux ]; then
	rm -f /boot/COPYING.linux
	dpkg-divert --package rpikernelhack --remove --rename /boot/COPYING.linux
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/README ]; then
	rm -f /boot/overlays/README
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/README
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/adau1977-adc.dtbo ]; then
	rm -f /boot/overlays/adau1977-adc.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/adau1977-adc.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/adau7002-simple.dtbo ]; then
	rm -f /boot/overlays/adau7002-simple.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/adau7002-simple.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/ads1015.dtbo ]; then
	rm -f /boot/overlays/ads1015.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/ads1015.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/ads1115.dtbo ]; then
	rm -f /boot/overlays/ads1115.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/ads1115.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/ads7846.dtbo ]; then
	rm -f /boot/overlays/ads7846.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/ads7846.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/akkordion-iqdacplus.dtbo ]; then
	rm -f /boot/overlays/akkordion-iqdacplus.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/akkordion-iqdacplus.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/allo-boss-dac-pcm512x-audio.dtbo ]; then
	rm -f /boot/overlays/allo-boss-dac-pcm512x-audio.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/allo-boss-dac-pcm512x-audio.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/allo-piano-dac-pcm512x-audio.dtbo ]; then
	rm -f /boot/overlays/allo-piano-dac-pcm512x-audio.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/allo-piano-dac-pcm512x-audio.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/allo-piano-dac-plus-pcm512x-audio.dtbo ]; then
	rm -f /boot/overlays/allo-piano-dac-plus-pcm512x-audio.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/allo-piano-dac-plus-pcm512x-audio.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/at86rf233.dtbo ]; then
	rm -f /boot/overlays/at86rf233.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/at86rf233.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/audioinjector-addons.dtbo ]; then
	rm -f /boot/overlays/audioinjector-addons.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/audioinjector-addons.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/audioinjector-wm8731-audio.dtbo ]; then
	rm -f /boot/overlays/audioinjector-wm8731-audio.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/audioinjector-wm8731-audio.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/audremap.dtbo ]; then
	rm -f /boot/overlays/audremap.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/audremap.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/bmp085_i2c-sensor.dtbo ]; then
	rm -f /boot/overlays/bmp085_i2c-sensor.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/bmp085_i2c-sensor.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/dht11.dtbo ]; then
	rm -f /boot/overlays/dht11.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/dht11.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/dionaudio-loco-v2.dtbo ]; then
	rm -f /boot/overlays/dionaudio-loco-v2.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/dionaudio-loco-v2.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/dionaudio-loco.dtbo ]; then
	rm -f /boot/overlays/dionaudio-loco.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/dionaudio-loco.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/dpi18.dtbo ]; then
	rm -f /boot/overlays/dpi18.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/dpi18.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/dpi24.dtbo ]; then
	rm -f /boot/overlays/dpi24.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/dpi24.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/dwc-otg.dtbo ]; then
	rm -f /boot/overlays/dwc-otg.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/dwc-otg.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/dwc2.dtbo ]; then
	rm -f /boot/overlays/dwc2.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/dwc2.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/enc28j60-spi2.dtbo ]; then
	rm -f /boot/overlays/enc28j60-spi2.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/enc28j60-spi2.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/enc28j60.dtbo ]; then
	rm -f /boot/overlays/enc28j60.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/enc28j60.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/fe-pi-audio.dtbo ]; then
	rm -f /boot/overlays/fe-pi-audio.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/fe-pi-audio.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/googlevoicehat-soundcard.dtbo ]; then
	rm -f /boot/overlays/googlevoicehat-soundcard.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/googlevoicehat-soundcard.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/gpio-ir.dtbo ]; then
	rm -f /boot/overlays/gpio-ir.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/gpio-ir.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/gpio-poweroff.dtbo ]; then
	rm -f /boot/overlays/gpio-poweroff.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/gpio-poweroff.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/hifiberry-amp.dtbo ]; then
	rm -f /boot/overlays/hifiberry-amp.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/hifiberry-amp.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/hifiberry-dac.dtbo ]; then
	rm -f /boot/overlays/hifiberry-dac.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/hifiberry-dac.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/hifiberry-dacplus.dtbo ]; then
	rm -f /boot/overlays/hifiberry-dacplus.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/hifiberry-dacplus.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/hifiberry-digi-pro.dtbo ]; then
	rm -f /boot/overlays/hifiberry-digi-pro.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/hifiberry-digi-pro.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/hifiberry-digi.dtbo ]; then
	rm -f /boot/overlays/hifiberry-digi.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/hifiberry-digi.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/hy28a.dtbo ]; then
	rm -f /boot/overlays/hy28a.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/hy28a.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/hy28b.dtbo ]; then
	rm -f /boot/overlays/hy28b.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/hy28b.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/i2c-bcm2708.dtbo ]; then
	rm -f /boot/overlays/i2c-bcm2708.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/i2c-bcm2708.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/i2c-gpio.dtbo ]; then
	rm -f /boot/overlays/i2c-gpio.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/i2c-gpio.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/i2c-mux.dtbo ]; then
	rm -f /boot/overlays/i2c-mux.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/i2c-mux.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/i2c-pwm-pca9685a.dtbo ]; then
	rm -f /boot/overlays/i2c-pwm-pca9685a.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/i2c-pwm-pca9685a.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/i2c-rtc.dtbo ]; then
	rm -f /boot/overlays/i2c-rtc.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/i2c-rtc.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/i2c-sensor.dtbo ]; then
	rm -f /boot/overlays/i2c-sensor.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/i2c-sensor.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/i2c0-bcm2708.dtbo ]; then
	rm -f /boot/overlays/i2c0-bcm2708.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/i2c0-bcm2708.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/i2c1-bcm2708.dtbo ]; then
	rm -f /boot/overlays/i2c1-bcm2708.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/i2c1-bcm2708.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/i2s-gpio28-31.dtbo ]; then
	rm -f /boot/overlays/i2s-gpio28-31.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/i2s-gpio28-31.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/iqaudio-dac.dtbo ]; then
	rm -f /boot/overlays/iqaudio-dac.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/iqaudio-dac.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/iqaudio-dacplus.dtbo ]; then
	rm -f /boot/overlays/iqaudio-dacplus.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/iqaudio-dacplus.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/iqaudio-digi-wm8804-audio.dtbo ]; then
	rm -f /boot/overlays/iqaudio-digi-wm8804-audio.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/iqaudio-digi-wm8804-audio.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/justboom-dac.dtbo ]; then
	rm -f /boot/overlays/justboom-dac.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/justboom-dac.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/justboom-digi.dtbo ]; then
	rm -f /boot/overlays/justboom-digi.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/justboom-digi.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/lirc-rpi.dtbo ]; then
	rm -f /boot/overlays/lirc-rpi.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/lirc-rpi.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/mcp23017.dtbo ]; then
	rm -f /boot/overlays/mcp23017.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/mcp23017.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/mcp23s17.dtbo ]; then
	rm -f /boot/overlays/mcp23s17.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/mcp23s17.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/mcp2515-can0.dtbo ]; then
	rm -f /boot/overlays/mcp2515-can0.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/mcp2515-can0.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/mcp2515-can1.dtbo ]; then
	rm -f /boot/overlays/mcp2515-can1.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/mcp2515-can1.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/mcp3008.dtbo ]; then
	rm -f /boot/overlays/mcp3008.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/mcp3008.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/midi-uart0.dtbo ]; then
	rm -f /boot/overlays/midi-uart0.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/midi-uart0.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/mmc.dtbo ]; then
	rm -f /boot/overlays/mmc.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/mmc.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/mz61581.dtbo ]; then
	rm -f /boot/overlays/mz61581.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/mz61581.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/pi3-act-led.dtbo ]; then
	rm -f /boot/overlays/pi3-act-led.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/pi3-act-led.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/pi3-disable-bt.dtbo ]; then
	rm -f /boot/overlays/pi3-disable-bt.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/pi3-disable-bt.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/pi3-disable-wifi.dtbo ]; then
	rm -f /boot/overlays/pi3-disable-wifi.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/pi3-disable-wifi.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/pi3-miniuart-bt.dtbo ]; then
	rm -f /boot/overlays/pi3-miniuart-bt.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/pi3-miniuart-bt.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/piscreen.dtbo ]; then
	rm -f /boot/overlays/piscreen.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/piscreen.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/piscreen2r.dtbo ]; then
	rm -f /boot/overlays/piscreen2r.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/piscreen2r.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/pisound.dtbo ]; then
	rm -f /boot/overlays/pisound.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/pisound.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/pitft22.dtbo ]; then
	rm -f /boot/overlays/pitft22.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/pitft22.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/pitft28-capacitive.dtbo ]; then
	rm -f /boot/overlays/pitft28-capacitive.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/pitft28-capacitive.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/pitft28-resistive.dtbo ]; then
	rm -f /boot/overlays/pitft28-resistive.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/pitft28-resistive.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/pitft35-resistive.dtbo ]; then
	rm -f /boot/overlays/pitft35-resistive.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/pitft35-resistive.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/pps-gpio.dtbo ]; then
	rm -f /boot/overlays/pps-gpio.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/pps-gpio.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/pwm-2chan.dtbo ]; then
	rm -f /boot/overlays/pwm-2chan.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/pwm-2chan.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/pwm.dtbo ]; then
	rm -f /boot/overlays/pwm.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/pwm.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/qca7000.dtbo ]; then
	rm -f /boot/overlays/qca7000.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/qca7000.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/raspidac3.dtbo ]; then
	rm -f /boot/overlays/raspidac3.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/raspidac3.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/rpi-backlight.dtbo ]; then
	rm -f /boot/overlays/rpi-backlight.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/rpi-backlight.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/rpi-cirrus-wm5102.dtbo ]; then
	rm -f /boot/overlays/rpi-cirrus-wm5102.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/rpi-cirrus-wm5102.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/rpi-dac.dtbo ]; then
	rm -f /boot/overlays/rpi-dac.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/rpi-dac.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/rpi-display.dtbo ]; then
	rm -f /boot/overlays/rpi-display.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/rpi-display.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/rpi-ft5406.dtbo ]; then
	rm -f /boot/overlays/rpi-ft5406.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/rpi-ft5406.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/rpi-proto.dtbo ]; then
	rm -f /boot/overlays/rpi-proto.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/rpi-proto.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/rpi-sense.dtbo ]; then
	rm -f /boot/overlays/rpi-sense.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/rpi-sense.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/rpi-tv.dtbo ]; then
	rm -f /boot/overlays/rpi-tv.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/rpi-tv.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/rra-digidac1-wm8741-audio.dtbo ]; then
	rm -f /boot/overlays/rra-digidac1-wm8741-audio.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/rra-digidac1-wm8741-audio.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/sc16is750-i2c.dtbo ]; then
	rm -f /boot/overlays/sc16is750-i2c.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/sc16is750-i2c.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/sc16is752-spi1.dtbo ]; then
	rm -f /boot/overlays/sc16is752-spi1.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/sc16is752-spi1.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/sdhost.dtbo ]; then
	rm -f /boot/overlays/sdhost.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/sdhost.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/sdio-1bit.dtbo ]; then
	rm -f /boot/overlays/sdio-1bit.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/sdio-1bit.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/sdio.dtbo ]; then
	rm -f /boot/overlays/sdio.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/sdio.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/sdtweak.dtbo ]; then
	rm -f /boot/overlays/sdtweak.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/sdtweak.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/smi-dev.dtbo ]; then
	rm -f /boot/overlays/smi-dev.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/smi-dev.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/smi-nand.dtbo ]; then
	rm -f /boot/overlays/smi-nand.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/smi-nand.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/smi.dtbo ]; then
	rm -f /boot/overlays/smi.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/smi.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/spi-gpio35-39.dtbo ]; then
	rm -f /boot/overlays/spi-gpio35-39.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/spi-gpio35-39.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/spi-rtc.dtbo ]; then
	rm -f /boot/overlays/spi-rtc.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/spi-rtc.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/spi0-cs.dtbo ]; then
	rm -f /boot/overlays/spi0-cs.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/spi0-cs.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/spi0-hw-cs.dtbo ]; then
	rm -f /boot/overlays/spi0-hw-cs.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/spi0-hw-cs.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/spi1-1cs.dtbo ]; then
	rm -f /boot/overlays/spi1-1cs.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/spi1-1cs.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/spi1-2cs.dtbo ]; then
	rm -f /boot/overlays/spi1-2cs.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/spi1-2cs.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/spi1-3cs.dtbo ]; then
	rm -f /boot/overlays/spi1-3cs.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/spi1-3cs.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/spi2-1cs.dtbo ]; then
	rm -f /boot/overlays/spi2-1cs.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/spi2-1cs.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/spi2-2cs.dtbo ]; then
	rm -f /boot/overlays/spi2-2cs.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/spi2-2cs.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/spi2-3cs.dtbo ]; then
	rm -f /boot/overlays/spi2-3cs.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/spi2-3cs.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/tinylcd35.dtbo ]; then
	rm -f /boot/overlays/tinylcd35.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/tinylcd35.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/uart1.dtbo ]; then
	rm -f /boot/overlays/uart1.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/uart1.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/vc4-fkms-v3d.dtbo ]; then
	rm -f /boot/overlays/vc4-fkms-v3d.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/vc4-fkms-v3d.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/vc4-kms-v3d.dtbo ]; then
	rm -f /boot/overlays/vc4-kms-v3d.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/vc4-kms-v3d.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/vga666.dtbo ]; then
	rm -f /boot/overlays/vga666.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/vga666.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/w1-gpio-pullup.dtbo ]; then
	rm -f /boot/overlays/w1-gpio-pullup.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/w1-gpio-pullup.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/w1-gpio.dtbo ]; then
	rm -f /boot/overlays/w1-gpio.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/w1-gpio.dtbo
	sync
fi
if [ -f /usr/share/rpikernelhack/overlays/wittypi.dtbo ]; then
	rm -f /boot/overlays/wittypi.dtbo
	dpkg-divert --package rpikernelhack --remove --rename /boot/overlays/wittypi.dtbo
	sync
fi
if [ -f /etc/default/raspberrypi-kernel ]; then
  . /etc/default/raspberrypi-kernel
  INITRD=No
  export INITRD
  RPI_INITRD=No
  export RPI_INITRD

fi
if [ -d "/etc/kernel/postinst.d" ]; then
  run-parts -v --report --exit-on-error --arg=+ --arg=/boot/kernel.img /etc/kernel/postinst.d
  run-parts -v --report --exit-on-error --arg=-v7+ --arg=/boot/kernel7.img /etc/kernel/postinst.d
fi
if [ -d "/etc/kernel/postinst.d/+" ]; then
  run-parts -v --report --exit-on-error --arg=+ --arg=/boot/kernel.img /etc/kernel/postinst.d/+
fi
if [ -d "/etc/kernel/postinst.d/-v7+" ]; then
  run-parts -v --report --exit-on-error --arg=-v7+ --arg=/boot/kernel7.img /etc/kernel/postinst.d/-v7+
fi
#DEBHELPER#
